challenge:
  name: Station 2
  title:
    en: The Challenge
    de: Der Ernstfall
  description:
    en: Can your character handle the situation?
    de: Hat dein Charakter die Lage im Griff?

inventory:
  name: Station 1
  title:
    en: Choose your inventory
    de: Auswahl des Inventars
  description:
    en: What do you rely on when it counts?
    de: Was bringst du mit, wenn es drauf ankommt?

tokenScanRequest:
  de: |-
    Charakter unten auf
    den Scanner legen
  en: |-
    Place your character
    on the scanner below
languages:
  en: English
  de: Deutsch

misc:
  character:
    en: Character
    de: Charakter
  challenge:
    en: Challenge
    de: Ernstfall
