challenge:
  title:
    en: Challenge
    de: Herausforderung
  description:
    en: Select a challenge and start playing!
    de: Wähle eine Herausforderung aus und spiele!
inventory:
  name: Station 1
  title:
    en: Choose your inventory
    de: Auswahl des Inventars
  description:
    en: What do you rely on when it counts?
    de: Was bringst du mit, wenn es drauf ankommt?

tokenScanRequest:
  de: |-
    Charakter unten auf
    den Scanner legen
  en: |-
    Place your character
    on the scanner below
languages:
  en: English
  de: Deutsch
