inventory:
  intro:
    name: Station 1
    title:
      en: Choose your inventory
      de: Auswahl des Inventars
    description:
      en: What do you rely on when it counts?
      de: Was bringst du mit, wenn es drauf ankommt?
  selection:
    title:
      en: Emergency inventory
      de: Inventar für den Ernstfall
    explanation:
      en: Tap on the skills and tools you want to add to your inventory.
      de: Tippe auf die Fähigkeiten und Ressourcen, die du zu deinem Inventar hinzufügen möchtest.
    lockedSlots:
      en: That defines you
      de: Das macht dich aus
    slots:
      en: Your inventory
      de: Dein Inventar
    slotEmpty:
      en: Empty
      de: Leer
    skills:
      en: Skills
      de: Fähigkeiten
    resources:
      en: Resources
      de: Ressourcen
    full:
      de: Inventar vollständig gefüllt
      en: Inventory full
    fullHint:
      en: Remove an item above to add another.
      de: Entferne oben einen Gegenstand, um einen anderen mitzunehmen.
    continueCondition:
      en: "When you're ready:"
      de: "Sobald du zufrieden bist:"
    continueHint:
      en: Continue to Station 2
      de: Weiter bei Station 2

challenge:
  name: Station 2
  title:
    en: The Challenge
    de: Der Ernstfall
  description:
    en: Can your character handle the situation?
    de: Hat dein Charakter die Lage im Griff?
  select:
    de: Situation lösen
    en: Resolve the situation
  unsolvable:
    de: |-
      Die Aufgabe werde ich wohl
      nicht lösen können. Das sollte
      jemand anderes versuchen.
    en: |-
      I probably won't be able to
      solve this problem. Someone
      else should try it.
  inventory:
    de: Das bringst du mit
    en: What you've got
  success:
    de: Gelöst!
    en: Solved!
  failure:
    de: Nicht gelöst!
    en: Not solved!
  next:
    de: Nächster Ernstfall
    en: Next challenge
  nextHint:
    de: Weiter geht's!
    en: Continue!
  retryHint:
    de: Gehe zurück zu Station 1
    en: Go back to station 1

tokenScanRequest:
  de: |-
    Charakter unten auf
    den Scanner legen
  en: |-
    Place your character
    on the scanner below
languages:
  en: English
  de: Deutsch

misc:
  character:
    en: Your character
    de: Dein Charakter
  challenge:
    en: Challenge
    de: Ernstfall
  invalidItem:
    title: Invalid item
    description: An invalid item ID was provided.
    icon: assets/icons/invalid.svg
  invalidCharacterType:
    title: Invalid character type
    description: The provided character type is invalid.
    image: assets/characters/invalid.svg
    imageCropped: assets/characters/invalid-portrait.svg

tokenError:
  name:
    en: Error
    de: Fehler
  title:
    en: Character chip malfunction
    de: Problem mit Charakter-Chip
  description:
    en: Error! There is an issue with your character chip.
    de: Fehler! Es gibt ein Problem mit deinem Charakter-Chip.
  instruction:
    en: Remove the character chip from the pad, wait 2 seconds, and place it back on.
    de: Nimm den Charakter-Chip von der Auflage, warte 2 Sekunden und lege ihn wieder auf.
  supportHint:
    en: Is the problem still occurring? Inform the staff.
    de: Besteht das Problem weiterhin? Informiere das Personal.
