inventory:
  intro:
    name: Station 1
    title:
      en: Choose your inventory
      de: Auswahl des Inventars
    description:
      en: What do you rely on when it counts?
      de: Was bringst du mit, wenn es drauf ankommt?
  selection:
    title:
      en: Emergency inventory
      de: Inventar für den Ernstfall
    explanation:
      en: Tap on the skills and resouces you want to add to your inventory to prepare for the scenarios in the next station.
      de: Tippe auf die Fähigkeiten und Ressourcen, die du zu deinem Inventar hinzufügen möchtest.
    lockedSlots:
      en: What you already have
      de: Das hast du schon
    slotLockedHint:
      en: You cannot change this inventory tray.
      de: Dieses Fach des Inventars kannst du nicht verändern.
    slots:
      en: Your selection
      de: Deine Auswahl
    slotEmpty:
      en: Empty
      de: Leer
    slotEmptyHint:
      en: You can still fill this inventory tray.
      de: Dieses Fach des Inventars kannst du noch befüllen.
    skills:
      en: Skills
      de: Fähigkeiten
    resources:
      en: Resources
      de: Ressourcen
    itemLockedHint:
      en: This item is part of your character and cannot be changed.
      de: Dieses Element gehört zu deinem Charakter und kann nicht verändert werden.
    full:
      de: Inventar vollständig gefüllt
      en: Inventory full
    fullHint:
      en: Remove an item above to add another.
      de: Entferne oben einen Gegenstand, um einen anderen mitzunehmen.
    continueCondition:
      en: "When you're done:"
      de: "Wenn du fertig bist:"
    continueHint:
      en: Continue on the other screen
      de: Weiter beim anderen Bildschirm

challenge:
  name: Station 2
  title:
    en: The Scenario
    de: Der Ernstfall
  description:
    en: Ready for this scenario?
    de: Bereit für den Ernstfall?
  difficulty:
    de: Schwierigkeit
    en: Difficulty
  difficulties:
    easy:
      de: Leicht
      en: Easy
    medium:
      de: Mittel
      en: Medium
    hard:
      de: Schwer
      en: Hard
  select:
    de: Ernstfall lösen
    en: Handle the situation
  assessmentHint:
    de: Prüfe, ob dein Inventar zum Ernstfall passt. Die Hinweise unten zeigen dir, was deinem Charakter fehlt.
    en: Check if your inventory is right for the scenario. The hints below show what your character is missing.
  unsolvable:
    overline:
      de: Es liegt nicht an dir, es liegt an deinem Charakter
      en: It’s not you — it’s your character
    title:
      de: |-
        Dein Charakter kann diesen
        Ernstfall nicht lösen!
      en: |-
        Your character cannot
        solve this situation!
    description:
      de: |-
        Aufgrund des vorgegebenen Inventarinhalts kommst du hier nur mit einer anderen Person weiter.
        Suche dir einen anderen Charakter oder eine anderen Ernstfall aus.
      en: |-
        Due to the provided inventory, you can only progress with another player.
        Choose a different character or a different scenario.
  inventory:
    de: Das bringst du mit
    en: What you've got
  skillCorrectHint:
    de: Diese Fähigkeit kannst du hier gut gebrauchen.
    en: This skills turned out to be useful.
  skillIncorrectHint:
    de: Diese Fähigkeit hilft hier leider nicht.
    en: This skill is not particularly useful here.
  resourceCorrectHint:
    de: Die­se Ressource kannst du hier gut ge­brau­chen.
    en: This resource turned out to be useful.
  resourceIncorrectHint:
    de: Diese Ressource hilft hier leider nicht.
    en: This resource is not particularly useful here.
  skillPresentHint:
    de: Gut gemacht! Diese Fähigkeit kannst du hier gut gebrauchen.
    en: Well done! This skill is useful here.
  skillMissingHint:
    de: Gehe zurück zum Inventar und suche etwas passendes!
    en: Go back to the inventory and find something useful.
  resourcePresentHint:
    de: Gut gemacht! Diese Ressource kannst du hier gut gebrauchen.
    en: Well done! This resource is useful here.
  resourceMissingHint:
    de: Gehe zurück zum Inventar und suche etwas passendes!
    en: Go back to the inventory and find something useful.
  success:
    de: Gelöst!
    en: Solved!
  failure:
    de: Nicht gelöst!
    en: Not solved!
  next:
    de: Nächster Ernstfall
    en: Next challenge
  nextHint:
    de: Weiter geht's!
    en: Continue!
  retryHint:
    de: Gehe zurück zu Station 1
    en: Go back to station 1

tokenScanRequest:
  de: |-
    Charakter unten auf
    den Scanner legen
  en: |-
    Place your character
    on the scanner below
languages:
  en: English
  de: Deutsch

misc:
  character:
    en: Your character
    de: Dein Charakter
  challenge:
    en: Scenario
    de: Ernstfall
  invalidItem:
    title: Invalid item
    description: An invalid item ID was provided.
    icon: assets/icons/invalid.svg
  invalidCharacterType:
    title: Invalid character type
    description: The provided character type is invalid.
    image: assets/characters/invalid.svg
    imageCropped: assets/characters/invalid-portrait.svg

tokenError:
  name:
    en: Error
    de: Fehler
  title:
    en: Character chip malfunction
    de: Problem mit Charakter-Chip
  description:
    en: Error! There is an issue with your character chip.
    de: Fehler! Es gibt ein Problem mit deinem Charakter-Chip.
  instruction:
    en: Remove the character chip from the pad, wait 2 seconds, and place it back on.
    de: Nimm den Charakter-Chip von der Auflage, warte 2 Sekunden und lege ihn wieder auf.
  supportHint:
    en: Is the problem still occurring? Inform the staff.
    de: Besteht das Problem weiterhin? Informiere das Personal.
