#!/usr/bin/env bash
if [[ "$(uname)" == "Linux" ]]; then
  SCRIPT_DIR=$(cd "${0%/*}" && pwd)
  PROJECT_DIR=$(cd "${SCRIPT_DIR}/.." && pwd)
  (
    set -x
    sudo chown root "${PROJECT_DIR}/node_modules/electron/dist/chrome-sandbox"
    sudo chmod 4755 "${PROJECT_DIR}/node_modules/electron/dist/chrome-sandbox"
  )
fi
